sudo: required

language: python

services:
    - docker

before_install:
    - docker version
    - docker-compose version

install:
    - docker build -t cyclopszhao/shadowsocks:latest versions/shadowsocks

script: true

before_deploy:
    - echo $DOCKER_USERNAME

deploy:
    provider: script
    script: sh docker_push.sh
    on:
        branch: master
