sudo: required

env:
    global:
        - REPO=$DOCKER_USERNAME/shadowsocks
        - COMMIT=${TRAVIS_COMMIT::8}

language: python

services:
    - docker

before_install:
    - docker version
    - docker-compose version

install:
    - docker build -t $REPO:$COMMIT versions/shadowsocks

script: true

after_success:
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker tag $REPO:$COMMIT $REPO:TAG
    - docker push $REPO:$TAG
    - docker logout

# before_deploy: true

# deploy: true
