sudo: required

env:
    - REPO=$DOCKER_USERNAME/shadowsocks
    - TAG=`if ["$TRAVIS_BRANCH" == "master"]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`

language: python

services:
    - docker

before_install:
    - docker version
    - docker-compose version
    - echo $REPO
    - echo $TAG

install:
    - docker build -t $REPO:$TAG versions/shadowsocks

script: true

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $REPO:$TAG
    - docker logout

# before_deploy: true

# deploy: true
