sudo: required

language: python

services:
    - docker

before_install:
    - docker version
    - docker-compose version

install:
    - docker build -t cyclopszhao/shadowsocks:latest versions/shadowsocks

script: true

after_success:
    - echo $DOCKER_USER
    - echo $DOCKER_PASS
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
    - docker push cyclopszhao/shadowsocks:latest
    - docker logout

# before_deploy: true

# deploy: true
