sudo: required

# env:
#     global:
#         - secure: LY9X/GqMZT5Q9oQRzg7mAkHdCnEsAkHXOi+KXcKz7GjECwkD3Zg9T9F3jRBuRsX3R3r9RV1+HpZ5SJpWes+xSovCH/+gpBSv0S1lRUADjIvU4me8x1FOzw7YfNJvZwtgC4M19E1CI2nxwvkM8gESochbyqsr62o4x68QfKZEy4B52qtKUM+VSk+tUHqDaKiXn8H+tn6UhyEZ01SuCWEmLdqKlB9p9a3NSfPcUn2zQB1Ixblpp6DgQfvV9uPin8NI5xJekH6c+93yr0tHT63Vm9iIQwxI7J0tE/2VitWjguxySme6aQvPbB+fCzL1zowW7oaW4bOipcVwjsCrt7dWjfKt4QfcEOz7IzlH4x9uPY1HSJJbOinwUxE8vRB29kESma35Hen2h68131ty6hhc9o65iamNa5NIuR3nkDF0nIXvEjO+WHIpzwkEx9X3akrcVGZ9SGRUoF6vIz3WeyrEkKKV3p9VPaX9RmJ7zjrJ5BQscFUH0/3wiiHUivtv54s1eD6rtPH0K9ZXJEJRIIHflHw+9GNqarS3dM2KNTg5h/h82THEWFoF6f6s6QleI98bcQOdWmiME/DGYlfM1lXDw5EXSBdgdebfh17VoLe/rCKRdnUnQXS0oQ3a1ePKydS8phDlmKXMTIeiwU2ANF/+Cz980PR+5kRvkwOsWWI8Fn0=
#         - secure: Wv5x68nPLWMT0+p8eJ4rpdk3meLFFsoYekkok8wNLGEDBAJwrccS+lH89aRW/EZqS1+Ivpp4yaCoNfh5unLTZr2vOS7/3bXWEcJFGSALyKG2jTa5hUAzlNSTNgsaxb/YMabASYT6KqtlGQfktanPVFewMndJ6UsNDTpAW9RzXSjCt8PfNlZf8Mh2pjP8Wm0cNKRovVtNNbJt3JuRrbGftPXcwMZ6Vux3KzmQJIiy/APALi+0Tnk+hMYd7i24iVB8l0LGSdJysmDtGwwWut/nAvOEB1wl1fFADcBgw8SFnf8yuLrGaVigFVISZZEpTcu24EemUzkMc8TpiZNFuOJxCYEwX+b0+F2o37lVOAI1KDQF3JW6/0RTfiMTLeEn13I4THda//su829rX9+C7jvtmLg2sCf9TkQMi3zRTfVC7sSqgmJ900dFZ+kn4KhshCzJEOTRwG4+lUjUPbF/Hs+w8lF/t7shwnRvogXb2Cn3x4PT0988LJ+SmBJwRTgzFI7awyhxTjKw2GVLlp9LNztdW/ruBwDziR/E3FrqLDQP7i37NYS0hHgRNpDhuo3+NF3c1EGAdA9Rki7JrCTYB4PaxCV2DiD+IjpQQAPY3MQs+lULawrPlfJwCbCcdVRBydUHGPlmqWgsqKrJ1Bsqkpcu6s0GthdEKloWjSXesAhuVD4=
#         - secure: gDbeKQOfRMzSZInMBedieM0DyFbn/vW8xA7PgJTx5vVKcY0Vj3HHcHlKooIbB5HuJ1bi/kHuafemf+t3fhw501eV2UY+0d7nAvFR5+sKjIKD87Kbi7XGpLvQV0cbab0RbF864g0AfTnTnWTtWW0oZDO+3BJZj9hoXqf9G3JsWMC8+uc4XI/6C6yNMryQAVsp95pvjBR4ZDKMmqUgvQVg2phq71EKIzSmMsHTGCom4VddETYpl/p6/WQJjy+kTba9ER1O8s1NLZOHvKqnBxHcm3d6KgkhGuXgMhD4eW9CqbQsEcDi2jb9Uf+RlvH6dTCuyf28t/G6f9zQb0cp+bbbJ9vWUP3lJisEsbFSsrTGnw1QPhbtUPmpIyxVIHdT1xCljbQ0DZmJktuOI6eNhqiXLBLPz3rr9e25mQvgxpSzgMN1YnBpWyU52iuOccridxQzqdhcYL3khulizGhYfHtoqKnzCuO0v3BjvjTxJfGgkLKoOue6QoRtYuLLSZlYQH17e6xCjvb0Okwll1ggAcx7TrD1FsKdrjzdsyN/4YKUcUOyx6wNsfyR7VR7s2AiStu1+9E6g7KMM9sKW/1+2NNqUxJa4hXtqBwmi/RK1yTERqOAuPN1+ktm5n8XnzkQkuR2FXcsmsYptdZDUJQl8JIJHhUYgbHC65mz4F3ql1Ix2YY=

language: python

services:
    - docker

before_install:
    - docker build -t cyclopszhao/shadowsocks:latest versions/shadowsocks
    - docker run cyclopszhao/shadowsocks:latest ssserver --help
    - docker run cyclopszhao/shadowsocks:latest sslocal --help
    - docker ps -a

# deploy:
#   provider: script
#   script: sh docker_push.sh
#   on:
#     branch: master
