version: '3'
services:
    shadowsocks:
        build:
            context: ./versions/shadowsocks
        command: ["sslocal", "-c", "/etc/shadowsocks.json"]
        image: shadowsocks:latest
        ports:
            - "1080:1080"
        restart: on-failure
        tty: true
        volumes:
            - ./shadowsocks.json:/etc/shadowsocks.json

