version: "3"
services:
    sslocal:
        command: ["sslocal", "-c", "/etc/sslocal.json"]
        image: cyclopszhao/shadowsocks:latest
        networks:
            - sslocal
        ports:
            - 1080:1080
        restart: on-failure
        tty: true
        volumes:
            - ./sslocal.json:/etc/sslocal.json

networks:
    sslocal:
        driver: bridge
