version: "3"
services:
    shadowsocks:
        command: ["ssserver", "-c", "/etc/ssserver.json"]
        image: cyclopszhao/shadowsocks:latest
        ports:
            - 8388:8388
        restart: on-failure
        tty: true
        volumes:
            - ./ssserver.json:/etc/ssserver.json

