version: '3'
services:
    shadowsocks:
        build:
            context: ./versions/shadowsocks
        command: ["ssserver", "-c", "/etc/shadowsocks.json"]
        image: cyclopszhao/shadowsocks:latest
        ports:
            - "8388:8388"
        restart: on-failure
        tty: true
        volumes:
            - ./shadowsocks-ssserver.json:/etc/shadowsocks.json

