version: '3'
services:
    shadowsocks:
        build:
            context: ./versions/shadowsocks
        command: ["sslocal", "-c", "/etc/sslocal.json"]
        image: cyclopszhao/shadowsocks:latest
        ports:
            - "1080:1080"
        restart: on-failure
        tty: true
        volumes:
            - ./sslocal.json:/etc/sslocal.json

