version: "3"
services:
    ssserver:
        command: ["ssserver", "-c", "/etc/ssserver.json"]
        image: cyclopszhao/shadowsocks:latest
        networks:
            - ssserver
        ports:
            - 8388:8388
        restart: on-failure
        tty: true
        volumes:
            - ./ssserver.json:/etc/ssserver.json

networks:
    ssserver:
        driver: bridge
